name: A-core APP CI/CD
on: 
  push:
    branches-ignore: 
      - 'doc/*'
      - 'feature/*'
  pull_request:
    branches-ignore: 
      - 'doc/*'
      - 'feature/*'  
  workflow_dispatch:
    inputs:
      version-type:
        description: 'Major or minor or patch?'     
        required: true
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'
          - 'none'

jobs:
  call:
    uses: XX9-YE-SONG/acore-cicd-templates/.github/workflows/acore-workflow.yml@main
    with:
      app-name: sample
      version-type: ${{ inputs.version-type }}
